version: "3"
services:
  test-db:
    image: postgres
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: stock-quotes-tests
    ports:
      - "5431:5432"
  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - test-db
    ports:
      - "3000:3000"
