version: "3"
services:
  test-db:
    image: postgres
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: stock-quotes-tests
    ports:
      - "5430:5432"
